icons = "awesome5"

[theme]
name = "plain"

[theme.overrides]
# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Classic Dark by Jason Heeris (http://heeris.id.au)
idle_bg = "#151515"
idle_fg = "#D0D0D0"
info_bg = "#75B5AA"
info_fg = "#151515"
good_bg = "#90A959"
good_fg = "#151515"
warning_bg = "#F4BF75"
warning_fg = "#151515"
critical_bg = "#AC4142"
critical_fg = "#151515"


[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/rjframe/.Mail/me_example_com/Inbox"]
threshold_warning = 2
threshold_critical = 10
display_type = "new"

[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/rjframe/.Mail/me_example_com/Inbox/Screener"]
threshold_warning = 5
threshold_critical = 15
display_type = "new"

[[block]]
block = "custom"
command = "cat ~/.cache/cmus_playing.txt"
interval = "once"
signal = 1
hide_when_empty = true

# TODO: Skip the file; call the script directly.
[[block]]
block = "custom"
command = "cat ~/.cache/weather.txt"
interval = 300

[[block]]
block = "networkmanager"
on_click = "kitty nmtui"
ap_format = "{ssid} ({strength})"

[[block]]
block = "battery"
interval = 300
format = "{percentage} ({time})"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_avail;G} GB ({mem_avail_percents})"
interval = 60

[[block]]
block = "cpu"
interval = 60

[[block]]
block = "temperature"
collapsed = true
interval = 120

[[block]]
block = "sound"
show_volume_when_muted = true

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
