if [ "$(cat /proc/$$/comm)" = 'zsh' ]; then
    GLOBAL="-g"
else
    GLOBAL=""
fi

alias $GLOBAL mv='mv -v'

alias ls='ls -lph --color=auto'
alias la='ls -A'
alias l='ls -CF'

# Recursive diff on two directories.
alias diffr='diff -rp'

# Usage: 'recent 5', etc.
alias recent='ls -1t | tail -n +2 | head -n'

alias $GLOBAL grep='grep --color=auto'
alias $GLOBAL fgrep='fgrep --color=auto'
alias $GLOBAL egrep='egrep --color=auto'

alias psg='ps -A | grep'

# alias make='clear && make'
alias pm='python manage.py'

alias open='xdg-open'

alias df='df -h'
alias du='du -h'

alias mkdir='mkdir -p'

# Pipe text to this
alias rot13="tr 'A-Za-z' 'N-ZA-Mn-za-m'"

# CentOS doesn't have tree.
if ! command -v tree >/dev/null; then
    alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
fi

if command -v notify-send >/dev/null; then
    # Add an "alert" alias for long running commands.
    # Ex: sleep 3; alert
    alias $GLOBAL alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
fi

alias svim='sudo vim'
alias vi=vim
alias gvim=vim

# Because I think I'm always in vim.
alias :e='vim'
alias :q='exit'
alias :qa='exit'

alias cargo-update="cargo install --list | grep -v '    ' | awk '{print $1}' \
    | xargs cargo install"

alias play="ansible-playbook --ask-become-pass -i inventory.yml"
alias playchk="ansible-playbook --syntax-check -i inventory.yml"

if command -v lsof >/dev/null; then
    alias listeners='sudo lsof -iTCP -sTCP:LISTEN -P'
fi

if [ "$TERM" = 'xterm-kitty' ]; then
    alias icat='kitty +kitten icat'
fi

alias web='w3m -dump -T text/html'

alias mkpdf='pdflatex -synctext=1 -interaction=nonstopmode'

# Begin a pomodoro timer.
alias pom="echo 'notify-send --urgency=normal \"STEP AWAY FROM THE COMPUTER\"' \
    | at now + 50 minutes"

# List pomodoro projects.
alias pomp="cut -f1 $HOME/.pom_log | sort | uniq"

# uPIM aliases
alias ue=upim-edit
alias uc=upim-contact
